joostlek/python-spotify

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_playback.ambr
tests/fixtures/devices.json
tests/test_playback.py

Add method to fetch devices

---

tests/conftest.py
tests/test_playback.py

Add test fixture for spotify client

Add test fixture for spotify client

---

pyproject.toml

Don't fail builds if coverage is incorrect

Don't fail builds if coverage is 100

---

poetry.lock
pyproject.toml
tests/conftest.py
tests/const.py
tests/test_client.py
tests/test_playback.py

Migrate to aioresponses

---

src/spotifyaio/spotify.py
tests/test_playback.py

More player modify calls

---

pyproject.toml
src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_user.ambr
tests/fixtures/current_user.json
tests/fixtures/user.json
tests/test_user.py

Add method to fetch users

---

src/spotifyaio/__init__.py
tests/test_playback.py
tests/test_playlist.py
tests/test_user.py

Complete exported objects

---

src/spotifyaio/spotify.py
tests/test_playlist.py

Fix requesting playlist with different ids

Fix requesting playlist with different ids

---

src/spotifyaio/spotify.py
tests/test_spotify.py

Support adding to queue

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/followed_artists.json
tests/test_spotify.py

Add support for fetching followed artists

Add support for fetching followed artists

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/category.json
tests/test_spotify.py

Add support for fetching a category

Add support for fetching a category

---

src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/artist.json
tests/test_spotify.py

Add support for fetching an artist

Add support for fetching an artist

---

.pre-commit-config.yaml
src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/show_episodes.json
tests/test_spotify.py

Add support for fetching episodes of a show

Add support for fetching episodes of a show

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr

Add images to artist

---

src/spotifyaio/spotify.py

Remove blocking call

---

src/spotifyaio/models.py

Make email nullable

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/categories.json
tests/test_spotify.py

Add support for fetching categories

Add support for fetching categories

---

src/spotifyaio/models.py
tests/__snapshots__/test_spotify.ambr

Add tracks in playlist

---

src/spotifyaio/models.py
tests/fixtures/saved_albums.json

Handle null album in saved albums

Handle null album in saved albums

---

src/spotifyaio/models.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/recently_played_tracks.json

Handle null context in played tracks

Handle null context in played tracks

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py

Make lowercasing album preserialization a hook

Make lowercasing album preserialization a hook

---

src/spotifyaio/spotify.py
tests/test_spotify.py

Fix sending JSON

---

src/spotifyaio/spotify.py

Add list of things still left and reoder

Add list of things still left and reoder

---

src/spotifyaio/spotify.py
tests/test_spotify.py

Save albums

---

src/spotifyaio/spotify.py
tests/test_spotify.py

Removing saved albums

---

src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/album_saved.json
tests/test_spotify.py

Check saved album

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/audio_features.json
tests/test_spotify.py

Add support for retrieving audio features

Add support for retrieving audio features

---

src/spotifyaio/models.py

Add audio dongle as supported DeviceType

Add audio dongle as supported DeviceType

---

src/spotifyaio/models.py

Rename Key enum values

---

src/spotifyaio/models.py

Should have caught this when adding CastVideo, but here it is.. =)

Add missing device type: CastAudio

---

src/spotifyaio/models.py

Add more device types

---

src/spotifyaio/models.py

Add Tablet device type

---

src/spotifyaio/models.py

Add Smartwatch device type

---

src/spotifyaio/models.py

Add time signature 1/4

---

src/spotifyaio/models.py

Add unknown device type

---

src/spotifyaio/models.py

Add GameConsole device type

---

src/spotifyaio/spotify.py
tests/test_spotify.py

Add method to remove save audiobooks

Add method to remove save audiobooks

---

src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/audiobooks_saved.json
tests/test_spotify.py

Add method to check if audiobooks are saved

Add method to check if audiobooks are saved

---

src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/shows_saved.json
tests/test_spotify.py

Add method to shows

---

src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/tracks_saved.json
tests/test_spotify.py

Add method to tracks

---

src/spotifyaio/models.py
src/spotifyaio/spotify.py
tests/__snapshots__/test_spotify.ambr
tests/fixtures/accounts_followed.json
tests/test_spotify.py

Add methods for following

---

.github/workflows/tests.yaml

Support Python 3.13

---

.github/workflows/linting.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
.github/workflows/typing.yaml
poetry.lock
pyproject.toml

Remove support for python 3.11

Remove support for python 3.11

---

pyproject.toml
src/spotifyaio/spotify.py
tests/test_spotify.py

Catch JSON decode errors
